<a href="https://colab.research.google.com/github/wayhome/101colab/blob/main/math_for_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.size

4

In [5]:
a.shape

(4,)

In [6]:
a.dtype

dtype('int64')

In [7]:
b = np.array([[1,2,3,4], [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b.size

8

In [9]:
b.shape

(2, 4)

In [10]:
b.dtype

dtype('int64')

In [11]:
b = np.array([1,2,3,4.0])
b.dtype

dtype('float64')

In [15]:
c = np.array([111,222,333,444], dtype="uint16")
c

array([111, 222, 333, 444], dtype=uint16)

In [18]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
d.shape

(3, 3)

In [20]:
d.size

9

In [21]:
a = np.zeros((3,4), dtype="uint32")
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

In [22]:
a[0,3] = 42
a[1,1] = 66
a

array([[ 0,  0,  0, 42],
       [ 0, 66,  0,  0],
       [ 0,  0,  0,  0]], dtype=uint32)

In [24]:
b = 11 * np.ones((3,2))
b

array([[11., 11.],
       [11., 11.],
       [11., 11.]])

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [30]:
a = np.random.randint(0,5,(3,4))
a

array([[1, 3, 4, 2],
       [2, 0, 0, 0],
       [3, 4, 2, 0]])

In [31]:
np.save("random.npy", a)

In [32]:
b = np.load("random.npy")
b

array([[1, 3, 4, 2],
       [2, 0, 0, 0],
       [3, 4, 2, 0]])